### ISSUE TITLE
All failed

### ISSUE THREAD

**Issue by demingry** [octave-online/octave-online-server#29]
I followed your instructions, step by step, failed on my physical server(centos7 nodejs8,10,14 ). Next failed on my digitalocean cloud sever. Many problems that I cannot post all of them. Different problem occurred every time npm install.

**Comment by demingry** [comment]
with your scripts

**Comment by demingry** [comment]
And nothing about my problems on Google.

**Comment by demingry** [comment]
Docker:

Step 3/7 : RUN hg clone --insecure -r 171a2857d6d1 http://www.octave.org/hg/octave
 ---> Running in 79fce36da166
warning: connection security to hg.savannah.gnu.org is disabled per current settings; communication is susceptible to eavesdropping and tampering
real URL is https://hg.savannah.gnu.org/hgweb/octave

**Comment by demingry** [comment]
octave-pkg Dockerfile:

RUN cd pkg-downloads && wget $PKG_BASE_URL/tsa-4.6.2.tar.gz && \
	LC_ALL=C /usr/local/bin/octave -q --eval "pkg install tsa-4.6.2.tar.gz;"

sourceforge : 20 redirections exceeded. cannot download

**Comment by sffc** [comment]
The warning about connection security to hg.savannah.gnu.org is expected.

For package installation, if Sourceforge is causing problems, you can skip the package installation step by removing `octave-pkg` and modifying `octave-oo` in *containers/oos-quick-start/docker-compose.yaml* as follows:

```
# OLD:
  octave-pkg:
    image: octaveonline/octave-pkg:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-pkg/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-stable:v1.0.0"]
    depends_on: ["octave-stable"]
  octave-oo:
    image: octaveonline/octave-oo:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-oo/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-pkg:v1.0.0"]
    depends_on: ["octave-pkg"]

# NEW:
  octave-oo:
    image: octaveonline/octave-oo:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-oo/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-stable:v1.0.0"]
    depends_on: ["octave-stable"]
```
